### ISSUE TITLE
task list for refresh

### ISSUE THREAD

**Issue by bradflood** [bradflood/sonar-pitest#3]
- [x] remove slf4j; change logger references to org.sonar.api.utils.log. (https://github.com/SonarSource/sonar-java/blob/master/sonar-java-plugin/src/main/java/org/sonar/plugins/java/JavaSquidSensor.java)

- [x] revisit unit tests 
** Mutant - done
** MutantStatus - done
** Mutator - done
** PitestComputer - done
** PitestCoverageComputer - done
** PitestMetrics - done
** PitestPlugin - done
** PitestRulesDefinition - done
** PitestSensor - done
** ProjectReport - done
** SourceFileReport
** XmlReportFinder - replace this; it's unnecessarily complicated
** XmlReportParser - done
** PitestMetricsKeys - removed

- [x] integrate kotlin language support. does it need to be a included in SensorDescriptor.onlyOnLanguages?  pitest does the language evaluation, and the plugin consumes the pitest report. In this case, it would not need to be exposed to SQ

- [ ] examine embedding HTML report as was done on OWASP DC (https://github.com/stevespringett/dependency-check-sonar-plugin/pull/40/commits/b1456dadbb031cf5429f1eeb7bc7bd22f6c79082)

- [x] change PitestSensorTest to be threadsafe (remove statics)

- [ ] implement backward compatibility with SQ 5.6 (https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/SonarRuntime.java)

add NewCoverage info to sensor based on Mutant line number.  this will require some more refactoring to expose the InputFile, at least for testing
